import SearchbarComponent from "./_components/SearchbarComponent";
import SidebarComponent from "./_components/SidebarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div>
      <SidebarComponent />
      <SearchbarComponent />
      {children}
    </div>
  );
}
